language: node_js
node_js:
        - "6"
services:
        - postgresql
        - redis
before_script:
         - create db mold_development
         - create db mold_test
         - psql -d mold_development -c 'create extension "uuid-ossp"'
         - psql -d mold_test -c 'create extension "uuid-ossp"'
         - apt install postgresql-contrib
         - npm install
         - npm install -g babel-cli gulp sequelize-cli mocha
         - npm test
